# Generated by Django 2.1.5 on 2019-01-28 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('conversation', models.UUIDField(default=uuid.uuid4)),
                ('rating', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='ratee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratee_interactions', to='interactions.Person'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rater_interactions', to='interactions.Person'),
        ),
    ]
